# Generated by Django 6.0.6 on 2026-06-12 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='time',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='service_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Incoming', 'Incoming'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
