# Generated by Django 6.0.6 on 2026-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_jobrequest_address_remove_jobrequest_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRequest',
        ),
    ]
