# Generated by Django 6.0.6 on 2026-06-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_jobvacancy_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='title',
            field=models.CharField(default='Untitled Job', max_length=255),
        ),
    ]
