# Generated by Django 6.0.6 on 2026-06-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_jobvacancy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
