# Generated by Django 6.0.6 on 2026-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
