# Generated by Django 6.0.6 on 2026-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workerprofile_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentlyRejectedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='rejection_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('permanently_rejected', 'Permanently Rejected')], default='pending', max_length=20),
        ),
    ]
