# Generated by Django 6.0.6 on 2026-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='WorkerRole',
        ),
    ]
