# Generated by Django 6.0.6 on 2026-06-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_phone_number_delete_workerrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
