# Generated by Django 6.0.6 on 2026-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/customers/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/workers/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
