# Generated by Django 6.0.6 on 2026-06-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_blockeduser_unique_together_blockeduser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_rating', models.IntegerField(default=5)),
                ('performance_rating', models.IntegerField(default=5)),
                ('service_quality_rating', models.IntegerField(default=5)),
                ('friendly_rating', models.IntegerField(default=5)),
                ('cost_efficiency_rating', models.IntegerField(default=5)),
                ('overall_rating', models.FloatField(default=5.0)),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.customerprofile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('worker', 'customer')},
            },
        ),
    ]
