# Generated by Django 6.0.6 on 2026-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_conversation_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='worker_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
