# Generated by Django 6.0.6 on 2026-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_customer_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='customer_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='worker_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
